### PR TITLE
mp: Change tuple_element_t to tuple_element for OSX build.

### PR DESCRIPTION
**Pull request by bunnei**

### CODE REVIEW

**Comment by lioncash** [comment]
You may want to just increment the XCode version used with travis [see here](https://docs.travis-ci.com/user/osx-ci-environment/)

**Comment by MerryMage** [comment]
Agreed w/ @lioncash

**Comment by MerryMage** [comment]
Not required.

**Comment by MerryMage** [comment]
(See also citra-emu/citra#2045.)

**Pull request closed without merging**
