### PR TITLE
emit_x64_vector: SSSE3 variant of EmitVectorCountLeadingZeros8()

### PR DESCRIPTION
**Pull request by lioncash**
pshufb lyfe

### CODE REVIEW

**Comment by FernandoS27** [comment]
is it me or the SSSE3 version seems faster and better than the AVX version?

**Comment by MerryMage** [comment]
Feel free to remove the AVX version.

**Comment by lioncash** [comment]
Done

**Comment by lioncash** [comment]
failure is due to travis being travis

**Pull request merged**
