### PR TITLE
[rfc] fuzz_arm: New ARM tests

### PR DESCRIPTION
**Pull request by MerryMage**
One thing I don't like about doing it this way is it duplicates validity checking across two places.

### CODE REVIEW

**Comment by MerryMage** [comment]
Comment: Should probably move this validity checker into the main codebase; check validity before translating instructions and remove the asserts that currently exist.

This would mean that this could also be reused in the disassembler if this is desirable.

**Comment by lioncash** [comment]
What other place is validity checking done at (just to make sure I'm on the same page)?

**Comment by MerryMage** [comment]
@lioncash

Currently just in the translator ([I am referring to the unpredictable instruction checks](https://github.com/MerryMage/dynarmic/blob/master/src/frontend/translate/translate_arm/data_processing.cpp#L119-L120).)

**Comment by lioncash** [comment]
Hmm, I guess if all the unpredictable checks come before the actual instruction functionality (and that assumption holds for all instructions), then perhaps a checker of some sort can be made that just does the checks before executing the instruction, so you'd have it in between like so:

```
[Instruction Decode] → [Unpredictable Checker] → [Instruction Translation]
```

which would also let them be used for other purposes.

**Comment by MerryMage** [comment]
Will do this eventually™.

**Pull request closed without merging**
