### PR TITLE
A64: Implement URECPE and URSQRTE

### PR DESCRIPTION
**Pull request by lioncash**

### CODE REVIEW

**Comment by lioncash** [comment]
Failure is due to the build timing out.

**Comment by MerryMage** [comment]
re math_util.h:

We could expose `RecipEstimate` available in `FPRecipEstimate.cpp` and `RecipSqrtEstimate` available in `FPRSqrtEstimate.cpp`.

Do note that those functions return an 8 bit number, and you will have to set the 9th bit.

**Comment by lioncash** [comment]
Ah, didn't know we already had the algorithms in place, will change this to use those.

**Comment by lioncash** [comment]
(same failure as before; build timed out)

**Pull request merged**
