### PR TITLE
Remove 32-bit-only `AddWithCarry` from IR emitter

### PR DESCRIPTION
**Pull request by SachinVin**
Remove "Legacy" AddWithCarry used in the A32 frontend, in favor of the generic one used in the A64 frontend. Also back port A32 equivalent of SetNZCV.

### CODE REVIEW

**Comment by MerryMage** [comment]
Thanks, this was something I was planning to do at some point. Especially once I figure out the best way to handle the NZ/NZC cases in A32.

Will do a proper review when I get time.

**Comment by SachinVin** [comment]
Sure, thanks. I was only planning to deal with `ADC` and `SBC` for now, although NZC should be a simple u8 `mov` right (atleast with the current implementation)? It might be a bit more work for A64 hosts, but it should be better than what is currently being emitted.

**Comment by MerryMage** [comment]
The issue with NZC is that you'll need to merge the carry from the barrel shifter with the NZ from the actual operation.

**Comment by SachinVin** [comment]
Ah right, I forgot that happens.

**Comment by MerryMage** [comment]
A follow-up PR for `SubWithCarry` removal would be accepted.

**Comment by SachinVin** [comment]
You're welcome! I'll PR sometime soon, once I get the chance.

**Pull request merged**
